### ISSUE TITLE
Support data test cases

### ISSUE THREAD

**Issue by StardustDL** [eXceediDeaL/edl-coderunner#2]
How about use diff to judge program, just like on online judge. ( use `judge` command )

Maybe add file's unique config, or directory work-item? Like `a.c.config` or `/a/.config`

How to organize data is also an important problem.

```
a/
  data/
    config.json
    input1
    output1
    ...
    judger
```

**Comment by eXceediDeaL** [comment]
To improve file support, add these:
- specific config and data
- use new class `WorkItem` instead of `str` for `currentFile`
- `new -d --dir` command, to create a directory for one work-item.
- `new -c --config` to create specific file config.
- `new -t --test` to create test cases, only support for directory item.
  - this will create `data` directory, and add some config files.
- after that, add `judge` command

These functions need more time to realize. Maybe in version `0.0.3` or `0.0.4`, full realization in `0.0.4`, the next alpha version.
